version: '3.8'

services:
  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ./consul/config.json:/consul/config/config.json
    command: "agent -config-file=/consul/config/config.json"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      consul:
        condition: service_healthy

  my-service-1:
    build:
      context: ./aspnet-app
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - consul

  my-service-2:
    build:
      context: ./aspnet-app
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - consul

  my-service-3:
    build:
      context: ./aspnet-app
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - consul